projects:
  yerliprod:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-1
        apiId: cl3etxyumfce7bt2rc3pewuoa4
        maxDepth: 2
extensions:
  amplify:
    version: 3
